development:
  port: 3315
  mem_limit: 128M
#  morphology: stem_en
  min_prefix_len: 3
  bin_path: '/usr/local/bin'
fastdev:
  port: 3315
  mem_limit: 128M
#  morphology: stem_en
  min_prefix_len: 3
  bin_path: '/usr/local/bin'
test:
  port: 3315
  mem_limit: 128M
#  morphology: stem_en
  min_prefix_len: 3
  bin_path: '/usr/local/bin'
production:
  port: 3315
  #address: db1.fluxx.ef.org
  mem_limit: 128M
#  morphology: stem_en
  min_prefix_len: 3
  bin_path: '/usr/local/bin'
  searchd_file_path: "<%= Rails.root %>/../../shared/sphinx/<%= Rails.env %>"
staging:
  port: 3315
  mem_limit: 128M
#  morphology: stem_en
  min_prefix_len: 3
  bin_path: '/usr/local/bin'
  searchd_file_path: "<%= Rails.root %>/../../shared/sphinx/<%= Rails.env %>"