development:
  port: 3315
  mem_limit: 128M
#  morphology: stem_en
  min_prefix_len: 3
  bin_path: '/usr/local/bin'
  max_matches: 100000
fastdev:
  port: 3315
  mem_limit: 128M
#  morphology: stem_en
  min_prefix_len: 3
  bin_path: '/usr/local/bin'
  max_matches: 100000
test:
  port: 3315
  mem_limit: 128M
#  morphology: stem_en
  min_prefix_len: 3
  bin_path: '/usr/local/bin'
  max_matches: 100000
production:
  port: 3315
  #address: db1.fluxx.ef.org
  mem_limit: 128M
#  morphology: stem_en
  min_prefix_len: 3
  bin_path: '/usr/local/bin'
  searchd_file_path: "<%= Rails.root %>/../../shared/sphinx/<%= Rails.env %>"
  max_matches: 100000
staging:
  port: 3315
  mem_limit: 128M
#  morphology: stem_en
  min_prefix_len: 3
  bin_path: '/usr/local/bin'
  searchd_file_path: "<%= Rails.root %>/../../shared/sphinx/<%= Rails.env %>"
  max_matches: 100000
